### ISSUE TITLE
mistake case

### ISSUE THREAD

**Issue by abdullah44gur** [jonTrent/PatienceDiff#18]
Hi, I'm using your code while comparing two sentences. But, I realized something went wrong. Your code compares each word of sentence letter by letter. Ok. If the head of word (first letter) is difference, your code does not compare correctly. It returns -1 -1 -1 unrestingly so on.

For example;
These sentences = "Flam, örenine bilet almışsanız onun hareket etmesini bekliyorsunuz." and "Alam, trenine bilet almışsanız sonun hareket etmesini bekliyorsunuz."

{ line: 'F', aIndex: 0, bIndex: -1 }
{ line: 'A', aIndex: -1, bIndex: 0 }
{ line: 'l', aIndex: 1, bIndex: 1 }
{ line: 'a', aIndex: 2, bIndex: 2 }
{ line: 'm', aIndex: 3, bIndex: 3 }
{ line: ' ', aIndex: 4, bIndex: 4 }
{ line: ',', aIndex: 5, bIndex: 5 }
{ line: ' ', aIndex: 6, bIndex: 6 }
{ line: 't', aIndex: 7, bIndex: -1 }
{ line: 'r', aIndex: 8, bIndex: -1 }
{ line: 'e', aIndex: 9, bIndex: -1 }
{ line: 'n', aIndex: 10, bIndex: -1 }
{ line: 'i', aIndex: 11, bIndex: -1 }
{ line: 'n', aIndex: 12, bIndex: -1 }
{ line: 'e', aIndex: 13, bIndex: -1 }
{ line: ' ', aIndex: 14, bIndex: -1 }
{ line: 'b', aIndex: 15, bIndex: -1 }
{ line: 'i', aIndex: 16, bIndex: -1 }
{ line: 'l', aIndex: 17, bIndex: -1 }
{ line: 'e', aIndex: 18, bIndex: -1 }
{ line: 't', aIndex: 19, bIndex: -1 }
{ line: ' ', aIndex: 20, bIndex: -1 }
{ line: 'a', aIndex: 21, bIndex: -1 }
{ line: 'l', aIndex: 22, bIndex: -1 }
{ line: 'm', aIndex: 23, bIndex: -1 }
{ line: 'ı', aIndex: 24, bIndex: -1 }
{ line: 'ş', aIndex: 25, bIndex: -1 }
{ line: 's', aIndex: 26, bIndex: -1 }
{ line: 'a', aIndex: 27, bIndex: -1 }
{ line: 'n', aIndex: 28, bIndex: -1 }
{ line: 'ı', aIndex: 29, bIndex: -1 }
{ line: 'z', aIndex: 30, bIndex: -1 }
{ line: ' ', aIndex: 31, bIndex: -1 }
{ line: 'o', aIndex: 32, bIndex: -1 }
{ line: 'n', aIndex: 33, bIndex: -1 }
{ line: 'u', aIndex: 34, bIndex: -1 }
{ line: 'n', aIndex: 35, bIndex: -1 }
{ line: ' ', aIndex: 36, bIndex: -1 }
{ line: 'h', aIndex: 37, bIndex: -1 }
{ line: 'a', aIndex: 38, bIndex: -1 }
{ line: 'r', aIndex: 39, bIndex: -1 }
{ line: 'e', aIndex: 40, bIndex: -1 }
{ line: 'k', aIndex: 41, bIndex: -1 }
{ line: 'e', aIndex: 42, bIndex: -1 }
{ line: 't', aIndex: 43, bIndex: -1 }
{ line: ' ', aIndex: 44, bIndex: -1 }
{ line: 'e', aIndex: 45, bIndex: -1 }
{ line: 't', aIndex: 46, bIndex: -1 }
{ line: 'm', aIndex: 47, bIndex: -1 }
{ line: 'e', aIndex: 48, bIndex: -1 }
{ line: 's', aIndex: 49, bIndex: -1 }
{ line: 'i', aIndex: 50, bIndex: -1 }
{ line: 'n', aIndex: 51, bIndex: -1 }
{ line: 'i', aIndex: 52, bIndex: -1 }
{ line: ' ', aIndex: 53, bIndex: -1 }
{ line: 'b', aIndex: 54, bIndex: -1 }
{ line: 'e', aIndex: 55, bIndex: -1 }
{ line: 'k', aIndex: 56, bIndex: -1 }
{ line: 'l', aIndex: 57, bIndex: -1 }
{ line: 'i', aIndex: 58, bIndex: -1 }
{ line: 'y', aIndex: 59, bIndex: -1 }
{ line: 'o', aIndex: 60, bIndex: -1 }
{ line: 'r', aIndex: 61, bIndex: -1 }
{ line: 's', aIndex: 62, bIndex: -1 }
{ line: 'u', aIndex: 63, bIndex: -1 }
{ line: 'n', aIndex: 64, bIndex: -1 }
{ line: 'u', aIndex: 65, bIndex: -1 }
{ line: 'z', aIndex: 66, bIndex: -1 }
{ line: ' ', aIndex: 67, bIndex: -1 }
{ line: 'ö', aIndex: -1, bIndex: 7 }
{ line: 'r', aIndex: -1, bIndex: 8 }
{ line: 'e', aIndex: -1, bIndex: 9 }
{ line: 'n', aIndex: -1, bIndex: 10 }
{ line: 'i', aIndex: -1, bIndex: 11 }
{ line: 'n', aIndex: -1, bIndex: 12 }
{ line: 'e', aIndex: -1, bIndex: 13 }
{ line: ' ', aIndex: -1, bIndex: 14 }
{ line: 'b', aIndex: -1, bIndex: 15 }
{ line: 'i', aIndex: -1, bIndex: 16 }
{ line: 'l', aIndex: -1, bIndex: 17 }
{ line: 'e', aIndex: -1, bIndex: 18 }
{ line: 't', aIndex: -1, bIndex: 19 }
{ line: ' ', aIndex: -1, bIndex: 20 }
{ line: 'a', aIndex: -1, bIndex: 21 }
{ line: 'l', aIndex: -1, bIndex: 22 }
{ line: 'm', aIndex: -1, bIndex: 23 }
{ line: 'ı', aIndex: -1, bIndex: 24 }
{ line: 'ş', aIndex: -1, bIndex: 25 }
{ line: 's', aIndex: -1, bIndex: 26 }
{ line: 'a', aIndex: -1, bIndex: 27 }
{ line: 'n', aIndex: -1, bIndex: 28 }
{ line: 'ı', aIndex: -1, bIndex: 29 }
{ line: 'z', aIndex: -1, bIndex: 30 }
{ line: ' ', aIndex: -1, bIndex: 31 }
{ line: 's', aIndex: -1, bIndex: 32 }
{ line: 'o', aIndex: -1, bIndex: 33 }
{ line: 'n', aIndex: -1, bIndex: 34 }
{ line: 'u', aIndex: -1, bIndex: 35 }
{ line: 'n', aIndex: -1, bIndex: 36 }
{ line: ' ', aIndex: -1, bIndex: 37 }
{ line: 'h', aIndex: -1, bIndex: 38 }
{ line: 'a', aIndex: -1, bIndex: 39 }
{ line: 'r', aIndex: -1, bIndex: 40 }
{ line: 'e', aIndex: -1, bIndex: 41 }
{ line: 'k', aIndex: -1, bIndex: 42 }
{ line: 'e', aIndex: -1, bIndex: 43 }
{ line: 't', aIndex: -1, bIndex: 44 }
{ line: ' ', aIndex: -1, bIndex: 45 }
{ line: 'e', aIndex: -1, bIndex: 46 }
{ line: 't', aIndex: -1, bIndex: 47 }
{ line: 'm', aIndex: -1, bIndex: 48 }
{ line: 'e', aIndex: -1, bIndex: 49 }
{ line: 's', aIndex: -1, bIndex: 50 }
{ line: 'i', aIndex: -1, bIndex: 51 }
{ line: 'n', aIndex: -1, bIndex: 52 }
{ line: 'i', aIndex: -1, bIndex: 53 }
{ line: ' ', aIndex: -1, bIndex: 54 }
{ line: 'b', aIndex: -1, bIndex: 55 }
{ line: 'e', aIndex: -1, bIndex: 56 }
{ line: 'k', aIndex: -1, bIndex: 57 }
{ line: 'l', aIndex: -1, bIndex: 58 }
{ line: 'i', aIndex: -1, bIndex: 59 }
{ line: 'y', aIndex: -1, bIndex: 60 }
{ line: 'o', aIndex: -1, bIndex: 61 }
{ line: 'r', aIndex: -1, bIndex: 62 }
{ line: 's', aIndex: -1, bIndex: 63 }
{ line: 'u', aIndex: -1, bIndex: 64 }
{ line: 'n', aIndex: -1, bIndex: 65 }
{ line: 'u', aIndex: -1, bIndex: 66 }
{ line: 'z', aIndex: -1, bIndex: 67 }
{ line: ' ', aIndex: -1, bIndex: 68 }

(I hope I could be explained it. you understand mistake case.)

**Comment by jonTrent** [comment]
Hmmm... When I run the PatienceDiff against the sentences provided (from within the Chrome DevTools), the results are correct.

```
x = "Flam, örenine bilet almışsanız onun hareket etmesini bekliyorsunuz.".split("")
(67) ['F', 'l', 'a', 'm', ',', ' ', 'ö', 'r', 'e', 'n', 'i', 'n', 'e', ' ', 'b', 'i', 'l', 'e', 't', ' ', 'a', 'l', 'm', 'ı', 'ş', 's', 'a', 'n', 'ı', 'z', ' ', 'o', 'n', 'u', 'n', ' ', 'h', 'a', 'r', 'e', 'k', 'e', 't', ' ', 'e', 't', 'm', 'e', 's', 'i', 'n', 'i', ' ', 'b', 'e', 'k', 'l', 'i', 'y', 'o', 'r', 's', 'u', 'n', 'u', 'z', '.']

y = "Alam, trenine bilet almışsanız sonun hareket etmesini bekliyorsunuz.".split("")
(68) ['A', 'l', 'a', 'm', ',', ' ', 't', 'r', 'e', 'n', 'i', 'n', 'e', ' ', 'b', 'i', 'l', 'e', 't', ' ', 'a', 'l', 'm', 'ı', 'ş', 's', 'a', 'n', 'ı', 'z', ' ', 's', 'o', 'n', 'u', 'n', ' ', 'h', 'a', 'r', 'e', 'k', 'e', 't', ' ', 'e', 't', 'm', 'e', 's', 'i', 'n', 'i', ' ', 'b', 'e', 'k', 'l', 'i', 'y', 'o', 'r', 's', 'u', 'n', 'u', 'z', '.']

patienceDiff(x,y)

{lines: Array(70), lineCountDeleted: 2, lineCountInserted: 3, lineCountMoved: 0}
lineCountDeleted: 2
lineCountInserted: 3
lineCountMoved: 0
lines: Array(70)
0: {line: 'F', aIndex: 0, bIndex: -1}
1: {line: 'A', aIndex: -1, bIndex: 0}
2: {line: 'l', aIndex: 1, bIndex: 1}
3: {line: 'a', aIndex: 2, bIndex: 2}
4: {line: 'm', aIndex: 3, bIndex: 3}
5: {line: ',', aIndex: 4, bIndex: 4}
6: {line: ' ', aIndex: 5, bIndex: 5}
7: {line: 'ö', aIndex: 6, bIndex: -1}
8: {line: 't', aIndex: -1, bIndex: 6}
9: {line: 'r', aIndex: 7, bIndex: 7}
10: {line: 'e', aIndex: 8, bIndex: 8}
11: {line: 'n', aIndex: 9, bIndex: 9}
12: {line: 'i', aIndex: 10, bIndex: 10}
13: {line: 'n', aIndex: 11, bIndex: 11}
14: {line: 'e', aIndex: 12, bIndex: 12}
15: {line: ' ', aIndex: 13, bIndex: 13}
16: {line: 'b', aIndex: 14, bIndex: 14}
17: {line: 'i', aIndex: 15, bIndex: 15}
18: {line: 'l', aIndex: 16, bIndex: 16}
19: {line: 'e', aIndex: 17, bIndex: 17}
20: {line: 't', aIndex: 18, bIndex: 18}
21: {line: ' ', aIndex: 19, bIndex: 19}
22: {line: 'a', aIndex: 20, bIndex: 20}
23: {line: 'l', aIndex: 21, bIndex: 21}
24: {line: 'm', aIndex: 22, bIndex: 22}
25: {line: 'ı', aIndex: 23, bIndex: 23}
26: {line: 'ş', aIndex: 24, bIndex: 24}
27: {line: 's', aIndex: 25, bIndex: 25}
28: {line: 'a', aIndex: 26, bIndex: 26}
29: {line: 'n', aIndex: 27, bIndex: 27}
30: {line: 'ı', aIndex: 28, bIndex: 28}
31: {line: 'z', aIndex: 29, bIndex: 29}
32: {line: ' ', aIndex: 30, bIndex: 30}
33: {line: 's', aIndex: -1, bIndex: 31}
34: {line: 'o', aIndex: 31, bIndex: 32}
35: {line: 'n', aIndex: 32, bIndex: 33}
36: {line: 'u', aIndex: 33, bIndex: 34}
37: {line: 'n', aIndex: 34, bIndex: 35}
38: {line: ' ', aIndex: 35, bIndex: 36}
39: {line: 'h', aIndex: 36, bIndex: 37}
40: {line: 'a', aIndex: 37, bIndex: 38}
41: {line: 'r', aIndex: 38, bIndex: 39}
42: {line: 'e', aIndex: 39, bIndex: 40}
43: {line: 'k', aIndex: 40, bIndex: 41}
44: {line: 'e', aIndex: 41, bIndex: 42}
45: {line: 't', aIndex: 42, bIndex: 43}
46: {line: ' ', aIndex: 43, bIndex: 44}
47: {line: 'e', aIndex: 44, bIndex: 45}
48: {line: 't', aIndex: 45, bIndex: 46}
49: {line: 'm', aIndex: 46, bIndex: 47}
50: {line: 'e', aIndex: 47, bIndex: 48}
51: {line: 's', aIndex: 48, bIndex: 49}
52: {line: 'i', aIndex: 49, bIndex: 50}
53: {line: 'n', aIndex: 50, bIndex: 51}
54: {line: 'i', aIndex: 51, bIndex: 52}
55: {line: ' ', aIndex: 52, bIndex: 53}
56: {line: 'b', aIndex: 53, bIndex: 54}
57: {line: 'e', aIndex: 54, bIndex: 55}
58: {line: 'k', aIndex: 55, bIndex: 56}
59: {line: 'l', aIndex: 56, bIndex: 57}
60: {line: 'i', aIndex: 57, bIndex: 58}
61: {line: 'y', aIndex: 58, bIndex: 59}
62: {line: 'o', aIndex: 59, bIndex: 60}
63: {line: 'r', aIndex: 60, bIndex: 61}
64: {line: 's', aIndex: 61, bIndex: 62}
65: {line: 'u', aIndex: 62, bIndex: 63}
66: {line: 'n', aIndex: 63, bIndex: 64}
67: {line: 'u', aIndex: 64, bIndex: 65}
68: {line: 'z', aIndex: 65, bIndex: 66}
69: {line: '.', aIndex: 66, bIndex: 67}
length: 70
```

- What specific environment are you using?  Ie, browser or NodeJS version...
- Also, how are you splitting the sentences into character arrays?

**Comment by abdullah44gur** [comment]
I am using Nodejs, it needs to differences in a specific area of my project. Node version is 19.3.0. If I used patienceDiff method without split(""), it is going on same problem. If I used patienceDiffPlus method.
I guess if the example sentence length is a little big number, sometimes it returns same problem. The problem happens usually it alines first aIndex all, after bIndex all. It cannot be comparison axiom.

Another example= 
Kurumsal Olarak Sosyal Medyada Yer Almak İçin Ne Yapmalı
kurumsal olarak sosyal medyada yer almak için ne yapmalı

{ line: 'K', aIndex: 0, bIndex: -1 }
{ line: 'u', aIndex: 1, bIndex: -1 }
{ line: 'r', aIndex: 2, bIndex: -1 }
{ line: 'u', aIndex: 3, bIndex: -1 }
{ line: 'm', aIndex: 4, bIndex: -1 }
{ line: 's', aIndex: 5, bIndex: -1 }
{ line: 'a', aIndex: 6, bIndex: -1 }
{ line: 'l', aIndex: 7, bIndex: -1 }
{ line: ' ', aIndex: 8, bIndex: -1 }
{ line: 'O', aIndex: 9, bIndex: -1 }
{ line: 'l', aIndex: 10, bIndex: -1 }
{ line: 'a', aIndex: 11, bIndex: -1 }
{ line: 'r', aIndex: 12, bIndex: -1 }
{ line: 'a', aIndex: 13, bIndex: -1 }
{ line: 'k', aIndex: 14, bIndex: -1 }
{ line: ' ', aIndex: 15, bIndex: -1 }
{ line: 'S', aIndex: 16, bIndex: -1 }
{ line: 'o', aIndex: 17, bIndex: -1 }
{ line: 's', aIndex: 18, bIndex: -1 }
{ line: 'y', aIndex: 19, bIndex: -1 }
{ line: 'a', aIndex: 20, bIndex: -1 }
{ line: 'l', aIndex: 21, bIndex: -1 }
{ line: ' ', aIndex: 22, bIndex: -1 }
{ line: 'M', aIndex: 23, bIndex: -1 }
{ line: 'e', aIndex: 24, bIndex: -1 }
{ line: 'd', aIndex: 25, bIndex: -1 }
{ line: 'y', aIndex: 26, bIndex: -1 }
{ line: 'a', aIndex: 27, bIndex: -1 }
{ line: 'd', aIndex: 28, bIndex: -1 }
{ line: 'a', aIndex: 29, bIndex: -1 }
{ line: ' ', aIndex: 30, bIndex: -1 }
{ line: 'Y', aIndex: 31, bIndex: -1 }
{ line: 'e', aIndex: 32, bIndex: -1 }
{ line: 'r', aIndex: 33, bIndex: -1 }
{ line: ' ', aIndex: 34, bIndex: -1 }
{ line: 'A', aIndex: 35, bIndex: -1 }
{ line: 'l', aIndex: 36, bIndex: -1 }
{ line: 'm', aIndex: 37, bIndex: -1 }
{ line: 'a', aIndex: 38, bIndex: -1 }
{ line: 'k', aIndex: 39, bIndex: -1 }
{ line: ' ', aIndex: 40, bIndex: -1 }
{ line: 'İ', aIndex: 41, bIndex: -1 }
{ line: 'k', aIndex: -1, bIndex: 0 }
{ line: 'u', aIndex: -1, bIndex: 1 }
{ line: 'r', aIndex: -1, bIndex: 2 }
{ line: 'u', aIndex: -1, bIndex: 3 }
{ line: 'm', aIndex: -1, bIndex: 4 }
{ line: 's', aIndex: -1, bIndex: 5 }
{ line: 'a', aIndex: -1, bIndex: 6 }
{ line: 'l', aIndex: -1, bIndex: 7 }
{ line: ' ', aIndex: -1, bIndex: 8 }
{ line: 'o', aIndex: -1, bIndex: 9 }
{ line: 'l', aIndex: -1, bIndex: 10 }
{ line: 'a', aIndex: -1, bIndex: 11 }
{ line: 'r', aIndex: -1, bIndex: 12 }
{ line: 'a', aIndex: -1, bIndex: 13 }
{ line: 'k', aIndex: -1, bIndex: 14 }
{ line: ' ', aIndex: -1, bIndex: 15 }
{ line: 's', aIndex: -1, bIndex: 16 }
{ line: 'o', aIndex: -1, bIndex: 17 }
{ line: 's', aIndex: -1, bIndex: 18 }
{ line: 'y', aIndex: -1, bIndex: 19 }
{ line: 'a', aIndex: -1, bIndex: 20 }
{ line: 'l', aIndex: -1, bIndex: 21 }
{ line: ' ', aIndex: -1, bIndex: 22 }
{ line: 'm', aIndex: -1, bIndex: 23 }
{ line: 'e', aIndex: -1, bIndex: 24 }
{ line: 'd', aIndex: -1, bIndex: 25 }
{ line: 'y', aIndex: -1, bIndex: 26 }
{ line: 'a', aIndex: -1, bIndex: 27 }
{ line: 'd', aIndex: -1, bIndex: 28 }
{ line: 'a', aIndex: -1, bIndex: 29 }
{ line: ' ', aIndex: -1, bIndex: 30 }
{ line: 'y', aIndex: -1, bIndex: 31 }
{ line: 'e', aIndex: -1, bIndex: 32 }
{ line: 'r', aIndex: -1, bIndex: 33 }
{ line: ' ', aIndex: -1, bIndex: 34 }
{ line: 'a', aIndex: -1, bIndex: 35 }
{ line: 'l', aIndex: -1, bIndex: 36 }
{ line: 'm', aIndex: -1, bIndex: 37 }
{ line: 'a', aIndex: -1, bIndex: 38 }
{ line: 'k', aIndex: -1, bIndex: 39 }
{ line: ' ', aIndex: -1, bIndex: 40 }
{ line: 'i', aIndex: -1, bIndex: 41 }  /* After letters compare correctly */
{ line: 'ç', aIndex: 42, bIndex: 42 }
{ line: 'i', aIndex: 43, bIndex: 43 }
{ line: 'n', aIndex: 44, bIndex: 44 }
{ line: ' ', aIndex: 45, bIndex: 45 }
{ line: 'N', aIndex: 46, bIndex: -1 }
{ line: 'n', aIndex: -1, bIndex: 46 }
{ line: 'e', aIndex: 47, bIndex: 47 }
{ line: ' ', aIndex: 48, bIndex: 48 }
{ line: 'Y', aIndex: 49, bIndex: -1 }
{ line: 'y', aIndex: -1, bIndex: 49 }
{ line: 'a', aIndex: 50, bIndex: 50 }
{ line: 'p', aIndex: 51, bIndex: 51 }
{ line: 'm', aIndex: 52, bIndex: 52 }
{ line: 'a', aIndex: 53, bIndex: 53 }
{ line: 'l', aIndex: 54, bIndex: 54 }
{ line: 'ı', aIndex: 55, bIndex: 55 }
{ line: ' ', aIndex: 56, bIndex: 56 }

**Comment by jonTrent** [comment]
Please provide a minimally reproducible code example that exhibits the error so that it can be examined further.

**Comment by abdullah44gur** [comment]
I have a lot of sentences. I mean I send a passage to this while loop. This passage has a lot of sentences. So, My purpose, it returns differences each sentence after the ngram spell checker analysis method. This method catches misspelling, miswriting. I'm not even playing with your code. I just send as a parameter to sentence.

`` eachWord : editTextArea(patienceDiff(textBefore.split(""),textAfter.split("")).lines) ``

**Comment by jonTrent** [comment]
That's a code excerpt, not a minimally reproducible code example...

**Comment by abdullah44gur** [comment]
I don't understand what kind of code sample you want. Because I'm not playing with your javascript function, I'm just passing sentences as parameters. In your code you can't compare then some letters and it is returning -1 -1. 🤔

**Comment by jonTrent** [comment]
My first response above, with the sample data provided, indicates the issue is not with the patienceDiff algorithm.  So, what I need is a fully functioning short program that reproduces the issue, so that I can examine the lead up and execution of the patienceDiff more closely.

**Comment by abdullah44gur** [comment]
OK bro. If you don't mind, could you please try this example? Maybe, I hope you will see the wrong cases very closer.

`patienceDiff("Kurumsal Olarak Sosyal Medyada Yer Almak İcin Ne Yapmalı?".split(""),"kurumsal olarak sosyal medyada yer almak için ne yapmalı?".split(""))`

**Comment by jonTrent** [comment]
Yep, there we go.  Thanks for the minimal code sample exemplifying the error, as now I'm able to reproduce the results you're seeing...  Will respond in a few hours when I have a block of time to diagnose...  More than likely a subtlety associated with UTF encoding...

**Comment by abdullah44gur** [comment]
I'm really glad I found a code example that I can show you for test it. This kind of situation usually happens with sentences that are large in length. I make it smaller by adding a comma dot between the words. Then it can make the comparison.
Good luck bro. 🤗 Btw thanks for the writing this code. It is really worked out.

_Also, Let this is another test example for you. 😉_
`patienceDiff("hamamları, mektepleri, tekkeleri ile kiremit kaplı süslü evleri ve dükkânları bulunan güzel bir şehir".split(""),
                "hamakları, mektepleri, tekkeleri ile kiremit kaplı süslü elleri ve dükkânları bulunan güzel bir şehir".split(""))`

**Comment by jonTrent** [comment]
Okay, I've narrowed the issue, and what you've stumbled into is an edge case of the PatienceDiff algorithm.  In short, the PatienceDiff algorithm relies on identifying the longest unique common subsequence.  That is, it seeks unique characters in both strings, and then uses the matches between these unique characters in each string as anchor points for identifying common substrings.  Consider for example the following, which exemplifies the issue:
```
patienceDiff("bbaaccddeeffgghhiijjkkllmmnnoopp", "aabbccddeegghhiijjkkllmmnnooppff")
```
Note that neither the first string nor the second string has any unique characters (ie, whereby a character only occurs once), and therefore the PatienceDiff does not have any common unique substring with which to even begin looking for the longest common subsequence.  And thus returns a result akin to what you (Abdullah06444) have been seeing...

As opposed to the following case:
```
patienceDiff("bacdefghijklmnop", "abcdeghijklmnopf")
```
Here, there is a slew of unique characters which are common between the first and second strings, and therefore a longest common subsequence can easily be picked out, and the algorithm is returning expected results.

That is, in the edge case, the patienceDiff algorithm is returning correct results per the original design of the algorithm...


**So what to do?**  There is obviously a pattern that can be picked out from the edge cases above which the patienceDiff algorithm is not designed to consider, so how to adjust the original design of the algorithm to account for these edge cases?

After a bit of thought, I believe the solution lies in tweaking the sub function `findUnique`, such that if there are no unique occurrences in the substring in question, that it instead returns the first occurrence of pairs, and if no pairs exist, then triplets, etc.  In this way, there will at least be some semi-unique characters with which the patienceDiff can consider when seeking the longest common subsequence, but I will need to explore this concept a bit further with testing.  The solution will likely be a third variant of the patienceDiff that is introduced, in order to ensure backward compatibility for all those finding the original design of the patienceDiff suitable for their needs.

I will spend a bit of time this upcoming weekend exploring this alternative and comment accordingly...

**Comment by abdullah44gur** [comment]
Hey, I want to say one more thing. If we compares two words that one is capital letters uppercase, the other is capital letters lowercase, patienceDiff algorithm does not match this two letters. I realized this, mistake cases. Maybe, it can be better, if you think two letters compare insensitively. Accuracy rate will be increased like this.

`patienceDiff("Konstantinopolis’in IV. Haçlı Seferi sonucu Latinler tarafından işgal edilmesi ve bölgeye Latinlerin de yerleşmesiyle değişik bir boyut kazanmış , Güney Marmara kıyıları başta olmak üzere , neredeyse tüm Balıkesir yöresi artık Türkler , Latinler ve Bizanslılar arasında bir mücadele alanına dönüşmüştür.".split(""),
"konstantinopolis’in IV. haçlı seferi sonuçu latinler tarafından işgal eğilmesi ve gölgeye latinlerin de yerleşmesiyle değişik bir boyun kazanmış , güney marmara kıyıları bata olmak üzere , neredeyse tüm balıkesir yöresi artık kürkler , latinler ve bizanslılar arasında bir mücadele alanına dönüşmüştür.".split(""))`

**Comment by jonTrent** [comment]
@Abdullah06444 please see proposed branch update [string-comparison-enhancement](https://github.com/jonTrent/PatienceDiff/tree/string-comparison-enhancement), and give that a try on your test cases.

**!!! - Note that when passing the parameters to `patienceDiff`, pass as strings rather than arrays. - !!!**

 (For details on the change, see the writeup at https://github.com/jonTrent/PatienceDiff/pull/19.)

**Comment by abdullah44gur** [comment]
@jonTrent thanks for all. 🤗  
I updated patienceDiff algorithm with your branch in my project. I don't longer encounter anything related to the mistake case. Is it not necessary to use split("") in parameters in new version?

**Comment by jonTrent** [comment]
Glad to hear that the tweak fixed the issue...

With respect to passing string vs array... If passing an array, the logic is assuming that the elements within the array can be multi character (ie, words or sentences) and therefore represents the traditional PatienceDiff implementation.

If passing strings, then the logic kicks in to begin consider chunks of the strings for uniqueness when attempting to find common unique occurrences between the two strings.  So yes, when comparing strings, don't split into an array.  Otherwise, if you split the strings into arrays, then you will see the regular PatienceDiff behavior which started this issue...

When I merge in the change, I will update the README with the nuance between passing strings vs arrays.
