### ISSUE TITLE
Kinda breaks if the example target text is duplicated.

### ISSUE THREAD

**Issue by sleekweasel** [jonTrent/PatienceDiff#20]
Firstly, thanks for coding this up - I was going to spend today cooking up the simple diff.

I forked it to host it on GitHub pages - https://sleekweasel.github.io/PatienceDiff/PatienceDiff.html - but seem to have found a bug:

Method: Duplicate the second panel's example text, hit the button

Expected: The original diff for the original examples, with a block of 'add' for the duplicated bit

Observed: A 'remove' for the whole of the first text, and an 'add' for the whole of the second text.

**Comment by jonTrent** [comment]
Glad the repo is of value... Believe you're running into the same issue as #18.  Try using branch "string-comparison-enhancement" as I believe that will solve the edge case you've encountered.

As an aside, I will merge in the "string-comparison-enhancement" in the near future into branch main to replace "dev", and eliminate branch "master".  Before doing so, I'm debating though the best means of providing some developer control of the chunking size and am leaning towards allowing the developer to pass an array of chunk sizes.  Eg, if the developer passes an array of [ 3, 5, 7 ] then the algorithm will try, in that order, chunking the strings until it finds unique common chunks between both strings...

**Comment by sleekweasel** [comment]
I assumed it was doing a line by line comparison because the output loop is line-based!

Thanks for the pointer - I'll merge that branch to my master.

Your sequence looks like the Fibonacci sequence. Maybe that would be a good default.

**Comment by sleekweasel** [comment]
Hi. That seems to have degraded things!

- I pulled your branch to my repo and shift-refreshed the .js script file so it showed up as version 3 instead of 2, but now I'm seeing the 'delete all/add all' display even for the default differences.

**Comment by jonTrent** [comment]
If I take the text from your fork, specifically...

```
// Opening comment
#include <stdio.h>

// Frobs foo heartily
int frobnitz(int foo)
{
    int i;
    for(i = 0; i < 10; i++)
    {
        printf("Your answer is: ");
        printf("%d\n", foo);
    }
}

int fact(int n)
{
    if(n > 1)
    {
        return fact(n-1) * n;
    }
    return 1;
}

int main(int argc, char **argv)
{
    frobnitz(fact(10));
}
```

...and...

```
#include <stdio.h>

int fib(int n)
{
    if(n > 2)
    {
        return fib(n-1) + fib(n-2);
    }
    return 1;
}

// Frobs foo heartily
int frobnitz(int foo)
{
    int i;
    for(i = 0; i < 10; i++)
    {
        printf("%d\n", foo);
    }
}

int main(int argc, char **argv)
{
    frobnitz(fib(10));
}
// Closing comment
```

...and run it through this repos `PatienceDiff.html` page, it comes up with the proper result...

```
-   // Opening comment
    #include <stdio.h>
    
+   int fib(int n)
+m  {
+       if(n > 2)
+m      {
+           return fib(n-1) + fib(n-2);
+m      }
+m      return 1;
+m  }
+m  
    // Frobs foo heartily
    int frobnitz(int foo)
    {
        int i;
        for(i = 0; i < 10; i++)
        {
-           printf("Your answer is: ");
            printf("%d\n", foo);
        }
    }
    
-   int fact(int n)
-m  {
-       if(n > 1)
-m      {
-           return fact(n-1) * n;
-m      }
-m      return 1;
-m  }
-m  
    int main(int argc, char **argv)
    {
-       frobnitz(fact(10));
+       frobnitz(fib(10));
    }
+   // Closing comment
```
Ie, PatienceDiffPlus properly shows the changes necessary to mutate the first block into the second block...

**Comment by sleekweasel** [comment]
Curious! I pulled your other branch with the fix for the original case with the duplicated example block into my main through the website - the only code I'm aware of changing myself is the presentation layer!

Maybe I picked the wrong branch... I'll need to look when I'm back at a laptop.

**Comment by jonTrent** [comment]
Closing issue as unable to replicate.  New issue can be opened if further details provided.
