### ISSUE TITLE
license

### ISSUE THREAD

**Issue by aaron13100** [jonTrent/PatienceDiff#9]
There doesn't seem to be a license file. What license is it?
thanks

**Comment by CactusPuppy** [comment]
Please be aware that not licensing your code means that people cannot legally use it in any of their projects.

See [No License | Choose a License](https://choosealicense.com/no-permission/) for more information.

**Comment by jonTrent** [comment]
@aaron13100 @CactusPuppy thanks for pointing out the omission.  Subsequently, have selected and included the UNLICENSE.
